-- Populate the module table with explicit IDs
INSERT INTO module (id, name, description)
VALUES (0, 'System', 'No description available for System module.'),
       (1, 'Account', 'No description available for Account module.'),
       (2, 'Scheduler', 'No description available for Scheduler module.'),
       (3, 'Babe', 'No description available for Babe module.'),
       (4, 'Timestamp', 'No description available for Timestamp module.'),
       (5, 'Parameters', 'No description available for Parameters module.'),
       (6, 'Balances', 'No description available for Balances module.'),
       (7, 'OneshotAccount', 'No description available for OneshotAccount module.'),
       (10, 'SmithMembers', 'No description available for SmithMembers module.'),
       (11, 'AuthorityMembers', 'No description available for AuthorityMembers module.'),
       (12, 'Authorship', 'No description available for Authorship module.'),
       (13, 'Offences', 'No description available for Offences module.'),
       (14, 'Historical', 'No description available for Historical module.'),
       (15, 'Session', 'No description available for Session module.'),
       (16, 'Grandpa', 'No description available for Grandpa module.'),
       (17, 'ImOnline', 'No description available for ImOnline module.'),
       (18, 'AuthorityDiscovery', 'No description available for AuthorityDiscovery module.'),
       (20, 'Sudo', 'No description available for Sudo module.'),
       (21, 'UpgradeOrigin', 'No description available for UpgradeOrigin module.'),
       (22, 'Preimage', 'No description available for Preimage module.'),
       (23, 'TechnicalCommittee', 'No description available for TechnicalCommittee module.'),
       (30, 'UniversalDividend', 'No description available for UniversalDividend module.'),
       (32, 'TransactionPayment', 'No description available for TransactionPayment module.'),
       (40, 'Wot', 'No description available for Wot module.'),
       (41, 'Identity', 'No description available for Identity module.'),
       (42, 'Membership', 'No description available for Membership module.'),
       (43, 'Certification', 'No description available for Certification module.'),
       (44, 'Distance', 'No description available for Distance module.'),
       (50, 'AtomicSwap', 'No description available for AtomicSwap module.'),
       (51, 'Multisig', 'No description available for Multisig module.'),
       (52, 'ProvideRandomness', 'No description available for ProvideRandomness module.'),
       (53, 'Proxy', 'No description available for Proxy module.'),
       (54, 'Utility', 'No description available for Utility module.'),
       (55, 'Treasury', 'No description available for Treasury module.'),
       (66, 'Quota', 'No description available for Quota module.');


-- Populate the function table with explicit IDs
INSERT INTO function (id, module_id, call_index, name, description)
VALUES (0, 0, 0, 'remark', 'Make some on-chain remark.  Can be executed by every `origin`.'),
       (1, 0, 1, 'set_heap_pages', 'Set the number of pages in the WebAssembly environment''s heap.'),
       (2, 0, 2, 'set_code', 'Set the new runtime code.'),
       (3, 0, 3, 'set_code_without_checks',
        'Set the new runtime code without doing any checks of the given `code`.  Note that runtime upgrades will not run if this is called with a not-increasing spec version!'),
       (4, 0, 4, 'set_storage', 'Set some items of storage.'),
       (5, 0, 5, 'kill_storage', 'Kill some items from storage.'),
       (6, 0, 6, 'kill_prefix',
        'Kill all storage items with a key that starts with the given prefix.  **NOTE:** We rely on the Root origin to provide us the number of subkeys under the prefix we are removing to accurately calculate the weight of this function.'),
       (7, 0, 7, 'remark_with_event', 'Make some on-chain remark and emit event.'),
       (8, 0, 9, 'authorize_upgrade',
        'Authorize an upgrade to a given `code_hash` for the runtime. The runtime can be supplied later.  This call requires Root origin.'),
       (9, 0, 10, 'authorize_upgrade_without_checks',
        'Authorize an upgrade to a given `code_hash` for the runtime. The runtime can be supplied later.  WARNING: This authorizes an upgrade that will take place without any safety checks, for example that the spec name remains the same and that the version number increases. Not recommended for normal use. Use `authorize_upgrade` instead.  This call requires Root origin.'),
       (10, 0, 11, 'apply_authorized_upgrade',
        'Provide the preimage (runtime binary) `code` for an upgrade that has been authorized.  If the authorization required a version check, this call will ensure the spec name remains unchanged and that the spec version has increased.  Depending on the runtime''s `OnSetCode` configuration, this function may directly apply the new `code` in the same block or attempt to schedule the upgrade.  All origins are allowed.'),
       (11, 1, 0, 'unlink_identity', 'Unlink the identity associated with the account.'),
       (12, 2, 0, 'schedule', 'Anonymously schedule a task.'),
       (13, 2, 1, 'cancel', 'Cancel an anonymously scheduled task.'),
       (14, 2, 2, 'schedule_named', 'Schedule a named task.'),
       (15, 2, 3, 'cancel_named', 'Cancel a named scheduled task.'),
       (16, 2, 4, 'schedule_after', 'Anonymously schedule a task after a delay.'),
       (17, 2, 5, 'schedule_named_after', 'Schedule a named task after a delay.'),
       (18, 2, 6, 'set_retry',
        'Set a retry configuration for a task so that, in case its scheduled run fails, it will be retried after `period` blocks, for a total amount of `retries` retries or until it succeeds.  Tasks which need to be scheduled for a retry are still subject to weight metering and agenda space, same as a regular task. If a periodic task fails, it will be scheduled normally while the task is retrying.  Tasks scheduled as a result of a retry for a periodic task are unnamed, non-periodic clones of the original task. Their retry configuration will be derived from the original task''s configuration, but will have a lower value for `remaining` than the original `total_retries`.'),
       (19, 2, 7, 'set_retry_named',
        'Set a retry configuration for a named task so that, in case its scheduled run fails, it will be retried after `period` blocks, for a total amount of `retries` retries or until it succeeds.  Tasks which need to be scheduled for a retry are still subject to weight metering and agenda space, same as a regular task. If a periodic task fails, it will be scheduled normally while the task is retrying.  Tasks scheduled as a result of a retry for a periodic task are unnamed, non-periodic clones of the original task. Their retry configuration will be derived from the original task''s configuration, but will have a lower value for `remaining` than the original `total_retries`.'),
       (20, 2, 8, 'cancel_retry', 'Removes the retry configuration of a task.'),
       (21, 2, 9, 'cancel_retry_named', 'Cancel the retry configuration of a named task.'),
       (22, 3, 0, 'report_equivocation',
        'Report authority equivocation/misbehavior. This method will verify the equivocation proof and validate the given key ownership proof against the extracted offender. If both are valid, the offence will be reported.'),
       (23, 3, 1, 'report_equivocation_unsigned',
        'Report authority equivocation/misbehavior. This method will verify the equivocation proof and validate the given key ownership proof against the extracted offender. If both are valid, the offence will be reported. This extrinsic must be called unsigned and it is expected that only block authors will call it (validated in `ValidateUnsigned`), as such if the block author is defined it will be defined as the equivocation reporter.'),
       (24, 3, 2, 'plan_config_change',
        'Plan an epoch config change. The epoch config change is recorded and will be enacted on the next call to `enact_epoch_change`. The config will be activated one epoch after. Multiple calls to this method will replace any existing planned config change that had not been enacted yet.'),
       (25, 4, 0, 'set',
        'Set the current time.  This call should be invoked exactly once per block. It will panic at the finalization phase, if this call hasn''t been invoked by that time.  The timestamp should be greater than the previous one by the amount specified by [`Config::MinimumPeriod`].  The dispatch origin for this call must be _None_.  This dispatch class is _Mandatory_ to ensure it gets executed in the block. Be aware that changing the complexity of this call could result exhausting the resources in a block to execute any other calls.  ## Complexity - `O(1)` (Note that implementations of `OnTimestampSet` must also be `O(1)`) - 1 storage read and 1 storage mutation (codec `O(1)` because of `DidUpdate::take` in   `on_finalize`) - 1 event handler `on_timestamp_set`. Must be `O(1)`.'),
       (26, 6, 0, 'transfer_allow_death',
        'Transfer some liquid free balance to another account.  `transfer_allow_death` will set the `FreeBalance` of the sender and receiver. If the sender''s account is below the existential deposit as a result of the transfer, the account will be reaped.  The dispatch origin for this call must be `Signed` by the transactor.'),
       (27, 6, 2, 'force_transfer',
        'Exactly as `transfer_allow_death`, except the origin must be root and the source account may be specified.'),
       (28, 6, 3, 'transfer_keep_alive',
        'Same as the [`transfer_allow_death`] call, but with a check that the transfer will not kill the origin account.  99% of the time you want [`transfer_allow_death`] instead.  [`transfer_allow_death`]: struct.Pallet.html#method.transfer'),
       (29, 6, 4, 'transfer_all',
        'Transfer the entire transferable balance from the caller account.  NOTE: This function only attempts to transfer _transferable_ balances. This means that any locked, reserved, or existential deposits (when `keep_alive` is `true`), will not be transferred by this function. To ensure that this function results in a killed account, you might need to prepare the account by removing any reference counters, storage deposits, etc...  The dispatch origin of this call must be Signed.  - `dest`: The recipient of the transfer. - `keep_alive`: A boolean to determine if the `transfer_all` operation should send all   of the funds the account has, causing the sender account to be killed (false), or   transfer everything except at least the existential deposit, which will guarantee to   keep the sender account alive (true).'),
       (30, 6, 5, 'force_unreserve', 'Unreserve some balance from a user by force.  Can only be called by ROOT.'),
       (31, 6, 8, 'force_set_balance',
        'Upgrade a specified account.  - `origin`: Must be `Signed`. - `who`: The account to be upgraded.  This will waive the transaction fee if at least all but 10% of the accounts needed to be upgraded. (We let some not have to be upgraded just in order to allow for the possibility of churn). Set the regular balance of a given account.  The dispatch origin for this call is `root`.'),
       (32, 6, 9, 'force_adjust_total_issuance',
        'Adjust the total issuance in a saturating way.  Can only be called by root and always needs a positive `delta`.  # Example'),
       (33, 6, 10, 'burn',
        'Burn the specified liquid free balance from the origin account.  If the origin''s account ends up below the existential deposit as a result of the burn and `keep_alive` is false, the account will be reaped.  Unlike sending funds to a _burn_ address, which merely makes the funds inaccessible, this `burn` operation will reduce total issuance by the amount _burned_.'),
       (34, 7, 0, 'create_oneshot_account',
        'Create an account that can only be consumed once  - `dest`: The oneshot account to be created. - `balance`: The balance to be transfered to this oneshot account.  Origin account is kept alive.'),
       (35, 7, 1, 'consume_oneshot_account',
        'Consume a oneshot account and transfer its balance to an account  - `block_height`: Must be a recent block number. The limit is `BlockHashCount` in the past. (this is to prevent replay attacks) - `dest`: The destination account. - `dest_is_oneshot`: If set to `true`, then a oneshot account is created at `dest`. Else, `dest` has to be an existing account.'),
       (36, 7, 2, 'consume_oneshot_account_with_remaining',
        'Consume a oneshot account then transfer some amount to an account, and the remaining amount to another account.  - `block_height`: Must be a recent block number.   The limit is `BlockHashCount` in the past. (this is to prevent replay attacks) - `dest`: The destination account. - `dest_is_oneshot`: If set to `true`, then a oneshot account is created at `dest`. Else, `dest` has to be an existing account. - `dest2`: The second destination account. - `dest2_is_oneshot`: If set to `true`, then a oneshot account is created at `dest2`. Else, `dest2` has to be an existing account. - `balance1`: The amount transfered to `dest`, the leftover being transfered to `dest2`.'),
       (37, 10, 0, 'invite_smith', 'Invite a member of the Web of Trust to attempt becoming a Smith.'),
       (38, 10, 1, 'accept_invitation', 'Accept an invitation to become a Smith (must have been invited first).'),
       (39, 10, 2, 'certify_smith', 'Certify an invited Smith, which can lead the certified to become a Smith.'),
       (40, 11, 0, 'go_offline', 'Request to leave the set of validators two sessions later.'),
       (41, 11, 1, 'go_online', 'Request to join the set of validators two sessions later.'),
       (42, 11, 2, 'set_session_keys', 'Declare new session keys to replace current ones.'),
       (43, 11, 3, 'remove_member', 'Remove a member from the set of validators.'),
       (44, 11, 4, 'remove_member_from_blacklist',
        'Remove a member from the blacklist. remove an identity from the blacklist'),
       (45, 15, 0, 'set_keys',
        'Sets the session key(s) of the function caller to `keys`. Allows an account to set its session key prior to becoming a validator. This doesn''t take effect until the next session.  The dispatch origin of this function must be signed.  ## Complexity - `O(1)`. Actual cost depends on the number of length of `T::Keys::key_ids()` which is   fixed.'),
       (46, 15, 1, 'purge_keys',
        'Removes any session key(s) of the function caller.  This doesn''t take effect until the next session.  The dispatch origin of this function must be Signed and the account must be either be convertible to a validator ID using the chain''s typical addressing system (this usually means being a controller account) or directly convertible into a validator ID (which usually means being a stash account).  ## Complexity - `O(1)` in number of key types. Actual cost depends on the number of length of   `T::Keys::key_ids()` which is fixed.'),
       (47, 16, 0, 'report_equivocation',
        'Report voter equivocation/misbehavior. This method will verify the equivocation proof and validate the given key ownership proof against the extracted offender. If both are valid, the offence will be reported.'),
       (48, 16, 1, 'report_equivocation_unsigned',
        'Report voter equivocation/misbehavior. This method will verify the equivocation proof and validate the given key ownership proof against the extracted offender. If both are valid, the offence will be reported.  This extrinsic must be called unsigned and it is expected that only block authors will call it (validated in `ValidateUnsigned`), as such if the block author is defined it will be defined as the equivocation reporter.'),
       (49, 16, 2, 'note_stalled',
        'Note that the current authority set of the GRANDPA finality gadget has stalled.  This will trigger a forced authority set change at the beginning of the next session, to be enacted `delay` blocks after that. The `delay` should be high enough to safely assume that the block signalling the forced change will not be re-orged e.g. 1000 blocks. The block production rate (which may be slowed down because of finality lagging) should be taken into account when choosing the `delay`. The GRANDPA voters based on the new authority will start voting on top of `best_finalized_block_number` for new finalized blocks. `best_finalized_block_number` should be the highest of the latest finalized block of all validators of the new authority set.  Only callable by root.'),
       (50, 17, 0, 'heartbeat',
        '## Complexity: - `O(K)` where K is length of `Keys` (heartbeat.validators_len)   - `O(K)`: decoding of length `K`'),
       (51, 20, 0, 'sudo', 'Authenticates the sudo key and dispatches a function call with `Root` origin.'),
       (52, 20, 1, 'sudo_unchecked_weight',
        'Authenticates the sudo key and dispatches a function call with `Root` origin. This function does not check the weight of the call, and instead allows the Sudo user to specify the weight of the call.  The dispatch origin for this call must be _Signed_.'),
       (53, 20, 2, 'set_key',
        'Authenticates the current sudo key and sets the given AccountId (`new`) as the new sudo key.'),
       (54, 20, 3, 'sudo_as',
        'Authenticates the sudo key and dispatches a function call with `Signed` origin from a given account.  The dispatch origin for this call must be _Signed_.'),
       (55, 20, 4, 'remove_key', 'Permanently removes the sudo key.  **This cannot be un-done.**'),
       (56, 21, 0, 'dispatch_as_root',
        'Dispatches a function call from root origin.  The weight of this call is defined by the caller.'),
       (57, 21, 1, 'dispatch_as_root_unchecked_weight',
        'Dispatches a function call from root origin. This function does not check the weight of the call, and instead allows the caller to specify the weight of the call.  The weight of this call is defined by the caller.'),
       (58, 22, 0, 'note_preimage',
        'Register a preimage on-chain.  If the preimage was previously requested, no fees or deposits are taken for providing the preimage. Otherwise, a deposit is taken proportional to the size of the preimage.'),
       (59, 22, 1, 'unnote_preimage',
        'Clear an unrequested preimage from the runtime storage.  If `len` is provided, then it will be a much cheaper operation.  - `hash`: The hash of the preimage to be removed from the store. - `len`: The length of the preimage of `hash`.'),
       (60, 22, 2, 'request_preimage',
        'Request a preimage be uploaded to the chain without paying any fees or deposits.  If the preimage requests has already been provided on-chain, we unreserve any deposit a user may have paid, and take the control of the preimage out of their hands.'),
       (61, 22, 3, 'unrequest_preimage',
        'Clear a previously made request for a preimage.  NOTE: THIS MUST NOT BE CALLED ON `hash` MORE TIMES THAN `request_preimage`.'),
       (62, 22, 4, 'ensure_updated',
        'Ensure that the a bulk of pre-images is upgraded.  The caller pays no fee if at least 90% of pre-images were successfully updated.'),
       (63, 23, 0, 'set_members',
        'Set the collective''s membership.  - `new_members`: The new member list. Be nice to the chain and provide it sorted. - `prime`: The prime member whose vote sets the default. - `old_count`: The upper bound for the previous number of members in storage. Used for   weight estimation.  The dispatch of this call must be `SetMembersOrigin`.  NOTE: Does not enforce the expected `MaxMembers` limit on the amount of members, but       the weight estimations rely on it to estimate dispatchable weight.  # WARNING:  The `pallet-collective` can also be managed by logic outside of the pallet through the implementation of the trait [`ChangeMembers`]. Any call to `set_members` must be careful that the member set doesn''t get out of sync with other logic managing the member set.  ## Complexity: - `O(MP + N)` where:   - `M` old-members-count (code- and governance-bounded)   - `N` new-members-count (code- and governance-bounded)   - `P` proposals-count (code-bounded)'),
       (64, 23, 1, 'execute',
        'Dispatch a proposal from a member using the `Member` origin.  Origin must be a member of the collective.  ## Complexity: - `O(B + M + P)` where: - `B` is `proposal` size in bytes (length-fee-bounded) - `M` members-count (code-bounded) - `P` complexity of dispatching `proposal`'),
       (65, 23, 2, 'propose',
        'Add a new proposal to either be voted on or executed directly.  Requires the sender to be member.  `threshold` determines whether `proposal` is executed directly (`threshold < 2`) or put up for voting.  ## Complexity - `O(B + M + P1)` or `O(B + M + P2)` where:   - `B` is `proposal` size in bytes (length-fee-bounded)   - `M` is members-count (code- and governance-bounded)   - branching is influenced by `threshold` where:     - `P1` is proposal execution complexity (`threshold < 2`)     - `P2` is proposals-count (code-bounded) (`threshold >= 2`)'),
       (66, 23, 3, 'vote',
        'Add an aye or nay vote for the sender to the given proposal.  Requires the sender to be a member.  Transaction fees will be waived if the member is voting on any particular proposal for the first time and the call is successful. Subsequent vote changes will charge a fee. ## Complexity - `O(M)` where `M` is members-count (code- and governance-bounded)'),
       (67, 23, 5, 'disapprove_proposal',
        'Disapprove a proposal, close, and remove it from the system, regardless of its current state.  Must be called by the Root origin.  Parameters: * `proposal_hash`: The hash of the proposal that should be disapproved.  ## Complexity O(P) where P is the number of max proposals'),
       (68, 23, 6, 'close',
        'Close a vote that is either approved, disapproved or whose voting period has ended.  May be called by any signed account in order to finish voting and close the proposal.  If called before the end of the voting period it will only close the vote if it is has enough votes to be approved or disapproved.  If called after the end of the voting period abstentions are counted as rejections unless there is a prime member set and the prime member cast an approval.  If the close operation completes successfully with disapproval, the transaction fee will be waived. Otherwise execution of the approved operation will be charged to the caller.  + `proposal_weight_bound`: The maximum amount of weight consumed by executing the closed proposal. + `length_bound`: The upper bound for the length of the proposal in storage. Checked via `storage::read` so it is `size_of::<u32>() == 4` larger than the pure length.  ## Complexity - `O(B + M + P1 + P2)` where:   - `B` is `proposal` size in bytes (length-fee-bounded)   - `M` is members-count (code- and governance-bounded)   - `P1` is the complexity of `proposal` preimage.   - `P2` is proposal-count (code-bounded)'),
       (69, 30, 0, 'claim_uds', 'Claim Universal Dividends.'),
       (70, 30, 1, 'transfer_ud', 'Transfer some liquid free balance to another account, in milliUD.'),
       (71, 30, 2, 'transfer_ud_keep_alive',
        'Transfer some liquid free balance to another account in milliUD and keep the account alive.'),
       (72, 41, 0, 'create_identity',
        'Create an identity for an existing account  - `owner_key`: the public key corresponding to the identity to be created  The origin must be allowed to create an identity.'),
       (73, 41, 1, 'confirm_identity',
        'Confirm the creation of an identity and give it a name  - `idty_name`: the name uniquely associated to this identity. Must match the validation rules defined by the runtime.  The identity must have been created using `create_identity` before it can be confirmed.'),
       (74, 41, 3, 'change_owner_key',
        'Change identity owner key.  - `new_key`: the new owner key. - `new_key_sig`: the signature of the encoded form of `IdtyIndexAccountIdPayload`.                  Must be signed by `new_key`.  The origin should be the old identity owner key.'),
       (75, 41, 4, 'revoke_identity',
        'Revoke an identity using a revocation signature  - `idty_index`: the index of the identity to be revoked. - `revocation_key`: the key used to sign the revocation payload. - `revocation_sig`: the signature of the encoded form of `RevocationPayload`.                     Must be signed by `revocation_key`.  Any signed origin can execute this call.'),
       (76, 41, 6, 'prune_item_identities_names',
        'Remove identity names from storage.  This function allows a privileged root origin to remove multiple identity names from storage in bulk.  - `origin` - The origin of the call. It must be root. - `names` - A vector containing the identity names to be removed from storage.'),
       (77, 41, 7, 'fix_sufficients',
        'Change sufficient reference count for a given key.  This function allows a privileged root origin to increment or decrement the sufficient reference count associated with a specified owner key.  - `origin` - The origin of the call. It must be root. - `owner_key` - The account whose sufficient reference count will be modified. - `inc` - A boolean indicating whether to increment (`true`) or decrement (`false`) the count. '),
       (78, 41, 8, 'link_account',
        'Link an account to an identity.  This function links a specified account to an identity, requiring both the account and the identity to sign the operation.  - `origin` - The origin of the call, which must have an associated identity index. - `account_id` - The account ID to link, which must sign the payload. - `payload_sig` - The signature with the linked identity.'),
       (79, 43, 0, 'add_cert', 'Add a new certification.'),
       (80, 43, 3, 'renew_cert', 'Renew an existing certification.'),
       (81, 43, 1, 'del_cert',
        'Remove one certification given the issuer and the receiver.  - `origin`: Must be `Root`.'),
       (82, 43, 2, 'remove_all_certs_received_by',
        'Remove all certifications received by an identity.  - `origin`: Must be `Root`.'),
       (83, 44, 0, 'request_distance_evaluation',
        'Request evaluation of the caller''s identity distance.  This function allows the caller to request an evaluation of their distance. A positive evaluation will lead to claiming or renewing membership, while a negative evaluation will result in slashing for the caller.'),
       (84, 44, 4, 'request_distance_evaluation_for',
        'Request evaluation of a target identity''s distance.  This function allows the caller to request an evaluation of a specific target identity''s distance. This action is only permitted for unvalidated identities.'),
       (85, 44, 1, 'update_evaluation',
        'Push an evaluation result to the pool.  This inherent function is called internally by validators to push an evaluation result to the evaluation pool.'),
       (86, 44, 2, 'force_update_evaluation',
        'Force push an evaluation result to the pool.  It is primarily used for testing purposes.  - `origin`: Must be `Root`.'),
       (87, 44, 3, 'force_valid_distance_status',
        'Force set the distance evaluation status of an identity.  It is primarily used for testing purposes.  - `origin`: Must be `Root`.'),
       (88, 50, 0, 'create_swap',
        'Register a new atomic swap, declaring an intention to send funds from origin to target on the current blockchain. The target can claim the fund using the revealed proof. If the fund is not claimed after `duration` blocks, then the sender can cancel the swap.  The dispatch origin for this call must be _Signed_.  - `target`: Receiver of the atomic swap. - `hashed_proof`: The blake2_256 hash of the secret proof. - `balance`: Funds to be sent from origin. - `duration`: Locked duration of the atomic swap. For safety reasons, it is recommended   that the revealer uses a shorter duration than the counterparty, to prevent the   situation where the revealer reveals the proof too late around the end block.'),
       (89, 50, 1, 'claim_swap',
        'Claim an atomic swap.  The dispatch origin for this call must be _Signed_.  - `proof`: Revealed proof of the claim. - `action`: Action defined in the swap, it must match the entry in blockchain. Otherwise   the operation fails. This is used for weight calculation.'),
       (90, 50, 2, 'cancel_swap',
        'Cancel an atomic swap. Only possible after the originally set duration has passed.  The dispatch origin for this call must be _Signed_.  - `target`: Target of the original atomic swap. - `hashed_proof`: Hashed proof of the original atomic swap.'),
       (91, 51, 0, 'as_multi_threshold_1',
        'Immediately dispatch a multi-signature call using a single approval from the caller.  The dispatch origin for this call must be _Signed_.  - `other_signatories`: The accounts (other than the sender) who are part of the multi-signature, but do not participate in the approval process. - `call`: The call to be executed.  Result is equivalent to the dispatched result.  ## Complexity O(Z + C) where Z is the length of the call and C its execution weight.'),
       (92, 51, 1, 'as_multi',
        'Register approval for a dispatch to be made from a deterministic composite account if approved by a total of `threshold - 1` of `other_signatories`.  If there are enough, then dispatch the call.  Payment: `DepositBase` will be reserved if this is the first approval, plus `threshold` times `DepositFactor`. It is returned once this dispatch happens or is cancelled.  The dispatch origin for this call must be _Signed_.  - `threshold`: The total number of approvals for this dispatch before it is executed. - `other_signatories`: The accounts (other than the sender) who can approve this dispatch. May not be empty. - `maybe_timepoint`: If this is the first approval, then this must be `None`. If it is not the first approval, then it must be `Some`, with the timepoint (block number and transaction index) of the first approval transaction. - `call`: The call to be executed.  NOTE: Unless this is the final approval, you will generally want to use `approve_as_multi` instead, since it only requires a hash of the call.  Result is equivalent to the dispatched result if `threshold` is exactly `1`. Otherwise on success, result is `Ok` and the result from the interior call, if it was executed, may be found in the deposited `MultisigExecuted` event.  ## Complexity - `O(S + Z + Call)`. - Up to one balance-reserve or unreserve operation. - One passthrough operation, one insert, both `O(S)` where `S` is the number of   signatories. `S` is capped by `MaxSignatories`, with weight being proportional. - One call encode & hash, both of complexity `O(Z)` where `Z` is tx-len. - One encode & hash, both of complexity `O(S)`. - Up to one binary search and insert (`O(logS + S)`). - I/O: 1 read `O(S)`, up to 1 mutate `O(S)`. Up to one remove. - One event. - The weight of the `call`. - Storage: inserts one item, value size bounded by `MaxSignatories`, with a deposit   taken for its lifetime of `DepositBase + threshold * DepositFactor`.'),
       (93, 51, 2, 'approve_as_multi',
        'Register approval for a dispatch to be made from a deterministic composite account if approved by a total of `threshold - 1` of `other_signatories`.  Payment: `DepositBase` will be reserved if this is the first approval, plus `threshold` times `DepositFactor`. It is returned once this dispatch happens or is cancelled.  The dispatch origin for this call must be _Signed_.  - `threshold`: The total number of approvals for this dispatch before it is executed. - `other_signatories`: The accounts (other than the sender) who can approve this dispatch. May not be empty. - `maybe_timepoint`: If this is the first approval, then this must be `None`. If it is not the first approval, then it must be `Some`, with the timepoint (block number and transaction index) of the first approval transaction. - `call_hash`: The hash of the call to be executed.  NOTE: If this is the final approval, you will want to use `as_multi` instead.  ## Complexity - `O(S)`. - Up to one balance-reserve or unreserve operation. - One passthrough operation, one insert, both `O(S)` where `S` is the number of   signatories. `S` is capped by `MaxSignatories`, with weight being proportional. - One encode & hash, both of complexity `O(S)`. - Up to one binary search and insert (`O(logS + S)`). - I/O: 1 read `O(S)`, up to 1 mutate `O(S)`. Up to one remove. - One event. - Storage: inserts one item, value size bounded by `MaxSignatories`, with a deposit   taken for its lifetime of `DepositBase + threshold * DepositFactor`.'),
       (94, 51, 3, 'cancel_as_multi',
        'Cancel a pre-existing, on-going multisig transaction. Any deposit reserved previously for this operation will be unreserved on success.  The dispatch origin for this call must be _Signed_.  - `threshold`: The total number of approvals for this dispatch before it is executed. - `other_signatories`: The accounts (other than the sender) who can approve this dispatch. May not be empty. - `timepoint`: The timepoint (block number and transaction index) of the first approval transaction for this dispatch. - `call_hash`: The hash of the call to be executed.  ## Complexity - `O(S)`. - Up to one balance-reserve or unreserve operation. - One passthrough operation, one insert, both `O(S)` where `S` is the number of   signatories. `S` is capped by `MaxSignatories`, with weight being proportional. - One encode & hash, both of complexity `O(S)`. - One event. - I/O: 1 read `O(S)`, one remove. - Storage: removes one item.'),
       (95, 52, 0, 'request', 'Request randomness.'),
       (96, 53, 0, 'proxy',
        'Dispatch the given `call` from an account that the sender is authorised for through `add_proxy`.  The dispatch origin for this call must be _Signed_.  Parameters: - `real`: The account that the proxy will make a call on behalf of. - `force_proxy_type`: Specify the exact proxy type to be used and checked for this call. - `call`: The call to be made by the `real` account.'),
       (97, 53, 1, 'add_proxy',
        'Register a proxy account for the sender that is able to make calls on its behalf.  The dispatch origin for this call must be _Signed_.  Parameters: - `proxy`: The account that the `caller` would like to make a proxy. - `proxy_type`: The permissions allowed for this proxy account. - `delay`: The announcement period required of the initial proxy. Will generally be zero.'),
       (98, 53, 2, 'remove_proxy',
        'Unregister a proxy account for the sender.  The dispatch origin for this call must be _Signed_.  Parameters: - `proxy`: The account that the `caller` would like to remove as a proxy. - `proxy_type`: The permissions currently enabled for the removed proxy account.'),
       (99, 53, 3, 'remove_proxies',
        'Unregister all proxy accounts for the sender.  The dispatch origin for this call must be _Signed_.  WARNING: This may be called on accounts created by `pure`, however if done, then the unreserved fees will be inaccessible. **All access to this account will be lost.**'),
       (100, 53, 4, 'create_pure',
        'Spawn a fresh new account that is guaranteed to be otherwise inaccessible, and initialize it with a proxy of `proxy_type` for `origin` sender.  Requires a `Signed` origin.  - `proxy_type`: The type of the proxy that the sender will be registered as over the new account. This will almost always be the most permissive `ProxyType` possible to allow for maximum flexibility. - `index`: A disambiguation index, in case this is called multiple times in the same transaction (e.g. with `utility::batch`). Unless you''re using `batch` you probably just want to use `0`. - `delay`: The announcement period required of the initial proxy. Will generally be zero.  Fails with `Duplicate` if this has already been called in this transaction, from the same sender, with the same parameters.  Fails if there are insufficient funds to pay for deposit.'),
       (101, 53, 5, 'kill_pure',
        'Removes a previously spawned pure proxy.  WARNING: **All access to this account will be lost.** Any funds held in it will be inaccessible.  Requires a `Signed` origin, and the sender account must have been created by a call to `pure` with corresponding parameters.  - `spawner`: The account that originally called `pure` to create this account. - `index`: The disambiguation index originally passed to `pure`. Probably `0`. - `proxy_type`: The proxy type originally passed to `pure`. - `height`: The height of the chain when the call to `pure` was processed. - `ext_index`: The extrinsic index in which the call to `pure` was processed.  Fails with `NoPermission` in case the caller is not a previously created pure account whose `pure` call has corresponding parameters.'),
       (102, 53, 6, 'announce',
        'Publish the hash of a proxy-call that will be made in the future.  This must be called some number of blocks before the corresponding `proxy` is attempted if the delay associated with the proxy relationship is greater than zero.  No more than `MaxPending` announcements may be made at any one time.  This will take a deposit of `AnnouncementDepositFactor` as well as `AnnouncementDepositBase` if there are no other pending announcements.  The dispatch origin for this call must be _Signed_ and a proxy of `real`.  Parameters: - `real`: The account that the proxy will make a call on behalf of. - `call_hash`: The hash of the call to be made by the `real` account.'),
       (103, 53, 7, 'remove_announcement',
        'Remove a given announcement.  May be called by a proxy account to remove a call they previously announced and return the deposit.  The dispatch origin for this call must be _Signed_.  Parameters: - `real`: The account that the proxy will make a call on behalf of. - `call_hash`: The hash of the call to be made by the `real` account.'),
       (104, 53, 8, 'reject_announcement',
        'Remove the given announcement of a delegate.  May be called by a target (proxied) account to remove a call that one of their delegates (`delegate`) has announced they want to execute. The deposit is returned.  The dispatch origin for this call must be _Signed_.  Parameters: - `delegate`: The account that previously announced the call. - `call_hash`: The hash of the call to be made.'),
       (105, 53, 9, 'proxy_announced',
        'Dispatch the given `call` from an account that the sender is authorized for through `add_proxy`.  Removes any corresponding announcement(s).  The dispatch origin for this call must be _Signed_.  Parameters: - `real`: The account that the proxy will make a call on behalf of. - `force_proxy_type`: Specify the exact proxy type to be used and checked for this call. - `call`: The call to be made by the `real` account.'),
       (106, 54, 0, 'batch',
        'Send a batch of dispatch calls.  May be called from any origin except `None`.  - `calls`: The calls to be dispatched from the same origin. The number of call must not   exceed the constant: `batched_calls_limit` (available in constant metadata).  If origin is root then the calls are dispatched without checking origin filter. (This includes bypassing `frame_system::Config::BaseCallFilter`).  ## Complexity - O(C) where C is the number of calls to be batched.  This will return `Ok` in all circumstances. To determine the success of the batch, an event is deposited. If a call failed and the batch was interrupted, then the `BatchInterrupted` event is deposited, along with the number of successful calls made and the error of the failed call. If all were successful, then the `BatchCompleted` event is deposited.'),
       (107, 54, 1, 'as_derivative',
        'Send a call through an indexed pseudonym of the sender.  Filter from origin are passed along. The call will be dispatched with an origin which use the same filter as the origin of this call.  NOTE: If you need to ensure that any account-based filtering is not honored (i.e. because you expect `proxy` to have been used prior in the call stack and you do not want the call restrictions to apply to any sub-accounts), then use `as_multi_threshold_1` in the Multisig pallet instead.  NOTE: Prior to version *12, this was called `as_limited_sub`.  The dispatch origin for this call must be _Signed_.'),
       (108, 54, 2, 'batch_all',
        'Send a batch of dispatch calls and atomically execute them. The whole transaction will rollback and fail if any of the calls failed.  May be called from any origin except `None`.  - `calls`: The calls to be dispatched from the same origin. The number of call must not   exceed the constant: `batched_calls_limit` (available in constant metadata).  If origin is root then the calls are dispatched without checking origin filter. (This includes bypassing `frame_system::Config::BaseCallFilter`).  ## Complexity - O(C) where C is the number of calls to be batched.'),
       (109, 54, 3, 'dispatch_as',
        'Dispatches a function call with a provided origin.  The dispatch origin for this call must be _Root_.  ## Complexity - O(1).'),
       (110, 54, 4, 'force_batch',
        'Send a batch of dispatch calls. Unlike `batch`, it allows errors and won''t interrupt.  May be called from any origin except `None`.  - `calls`: The calls to be dispatched from the same origin. The number of call must not   exceed the constant: `batched_calls_limit` (available in constant metadata).  If origin is root then the calls are dispatch without checking origin filter. (This includes bypassing `frame_system::Config::BaseCallFilter`).  ## Complexity - O(C) where C is the number of calls to be batched.'),
       (111, 54, 5, 'with_weight',
        'Dispatch a function call with a specified weight.  This function does not check the weight of the call, and instead allows the Root origin to specify the weight of the call.  The dispatch origin for this call must be _Root_.'),
       (112, 55, 3, 'spend_local',
        'Propose and approve a spend of treasury funds.  ## Dispatch Origin  Must be [`Config::SpendOrigin`] with the `Success` value being at least `amount`.  ### Details NOTE: For record-keeping purposes, the proposer is deemed to be equivalent to the beneficiary.  ### Parameters - `amount`: The amount to be transferred from the treasury to the `beneficiary`. - `beneficiary`: The destination account for the transfer.  ## Events  Emits [`Event::SpendApproved`] if successful.'),
       (113, 55, 4, 'remove_approval',
        'Force a previously approved proposal to be removed from the approval queue.  ## Dispatch Origin  Must be [`Config::RejectOrigin`].  ## Details  The original deposit will no longer be returned.  ### Parameters - `proposal_id`: The index of a proposal  ### Complexity - O(A) where `A` is the number of approvals  ### Errors - [`Error::ProposalNotApproved`]: The `proposal_id` supplied was not found in the   approval queue, i.e., the proposal has not been approved. This could also mean the   proposal does not exist altogether, thus there is no way it would have been approved   in the first place.'),
       (114, 55, 5, 'spend',
        'Propose and approve a spend of treasury funds.  ## Dispatch Origin  Must be [`Config::SpendOrigin`] with the `Success` value being at least `amount` of `asset_kind` in the native asset. The amount of `asset_kind` is converted for assertion using the [`Config::BalanceConverter`].  ## Details  Create an approved spend for transferring a specific `amount` of `asset_kind` to a designated beneficiary. The spend must be claimed using the `payout` dispatchable within the [`Config::PayoutPeriod`].  ### Parameters - `asset_kind`: An indicator of the specific asset class to be spent. - `amount`: The amount to be transferred from the treasury to the `beneficiary`. - `beneficiary`: The beneficiary of the spend. - `valid_from`: The block number from which the spend can be claimed. It can refer to   the past if the resulting spend has not yet expired according to the   [`Config::PayoutPeriod`]. If `None`, the spend can be claimed immediately after   approval.  ## Events  Emits [`Event::AssetSpendApproved`] if successful.'),
       (115, 55, 6, 'payout',
        'Claim a spend.  ## Dispatch Origin  Must be signed  ## Details  Spends must be claimed within some temporal bounds. A spend may be claimed within one [`Config::PayoutPeriod`] from the `valid_from` block. In case of a payout failure, the spend status must be updated with the `check_status` dispatchable before retrying with the current function.  ### Parameters - `index`: The spend index.  ## Events  Emits [`Event::Paid`] if successful.'),
       (116, 55, 7, 'check_status',
        'Check the status of the spend and remove it from the storage if processed.  ## Dispatch Origin  Must be signed.  ## Details  The status check is a prerequisite for retrying a failed payout. If a spend has either succeeded or expired, it is removed from the storage by this function. In such instances, transaction fees are refunded.  ### Parameters - `index`: The spend index.  ## Events  Emits [`Event::PaymentFailed`] if the spend payout has failed. Emits [`Event::SpendProcessed`] if the spend payout has succeed.'),
       (117, 55, 8, 'void_spend',
        'Void previously approved spend.  ## Dispatch Origin  Must be [`Config::RejectOrigin`].  ## Details  A spend void is only possible if the payout has not been attempted yet.  ### Parameters - `index`: The spend index.  ## Events  Emits [`Event::AssetSpendVoided`] if successful.');
